# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/devinlynch/Desktop/Repos/codecrafters-git-c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/devinlynch/Desktop/Repos/codecrafters-git-c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/devinlynch/Desktop/Repos/codecrafters-git-c/CMakeFiles /Users/devinlynch/Desktop/Repos/codecrafters-git-c//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/devinlynch/Desktop/Repos/codecrafters-git-c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named git

# Build rule for target.
git: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 git
.PHONY : git

# fast build rule for target.
git/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/build
.PHONY : git/fast

src/cmd/catfile.o: src/cmd/catfile.c.o
.PHONY : src/cmd/catfile.o

# target to build an object file
src/cmd/catfile.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/catfile.c.o
.PHONY : src/cmd/catfile.c.o

src/cmd/catfile.i: src/cmd/catfile.c.i
.PHONY : src/cmd/catfile.i

# target to preprocess a source file
src/cmd/catfile.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/catfile.c.i
.PHONY : src/cmd/catfile.c.i

src/cmd/catfile.s: src/cmd/catfile.c.s
.PHONY : src/cmd/catfile.s

# target to generate assembly for a file
src/cmd/catfile.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/catfile.c.s
.PHONY : src/cmd/catfile.c.s

src/cmd/hashobject.o: src/cmd/hashobject.c.o
.PHONY : src/cmd/hashobject.o

# target to build an object file
src/cmd/hashobject.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/hashobject.c.o
.PHONY : src/cmd/hashobject.c.o

src/cmd/hashobject.i: src/cmd/hashobject.c.i
.PHONY : src/cmd/hashobject.i

# target to preprocess a source file
src/cmd/hashobject.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/hashobject.c.i
.PHONY : src/cmd/hashobject.c.i

src/cmd/hashobject.s: src/cmd/hashobject.c.s
.PHONY : src/cmd/hashobject.s

# target to generate assembly for a file
src/cmd/hashobject.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/hashobject.c.s
.PHONY : src/cmd/hashobject.c.s

src/cmd/init.o: src/cmd/init.c.o
.PHONY : src/cmd/init.o

# target to build an object file
src/cmd/init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/init.c.o
.PHONY : src/cmd/init.c.o

src/cmd/init.i: src/cmd/init.c.i
.PHONY : src/cmd/init.i

# target to preprocess a source file
src/cmd/init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/init.c.i
.PHONY : src/cmd/init.c.i

src/cmd/init.s: src/cmd/init.c.s
.PHONY : src/cmd/init.s

# target to generate assembly for a file
src/cmd/init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/init.c.s
.PHONY : src/cmd/init.c.s

src/cmd/lstree.o: src/cmd/lstree.c.o
.PHONY : src/cmd/lstree.o

# target to build an object file
src/cmd/lstree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/lstree.c.o
.PHONY : src/cmd/lstree.c.o

src/cmd/lstree.i: src/cmd/lstree.c.i
.PHONY : src/cmd/lstree.i

# target to preprocess a source file
src/cmd/lstree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/lstree.c.i
.PHONY : src/cmd/lstree.c.i

src/cmd/lstree.s: src/cmd/lstree.c.s
.PHONY : src/cmd/lstree.s

# target to generate assembly for a file
src/cmd/lstree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/lstree.c.s
.PHONY : src/cmd/lstree.c.s

src/cmd/writetree.o: src/cmd/writetree.c.o
.PHONY : src/cmd/writetree.o

# target to build an object file
src/cmd/writetree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/writetree.c.o
.PHONY : src/cmd/writetree.c.o

src/cmd/writetree.i: src/cmd/writetree.c.i
.PHONY : src/cmd/writetree.i

# target to preprocess a source file
src/cmd/writetree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/writetree.c.i
.PHONY : src/cmd/writetree.c.i

src/cmd/writetree.s: src/cmd/writetree.c.s
.PHONY : src/cmd/writetree.s

# target to generate assembly for a file
src/cmd/writetree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/cmd/writetree.c.s
.PHONY : src/cmd/writetree.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/main.c.s
.PHONY : src/main.c.s

src/storage/object.o: src/storage/object.c.o
.PHONY : src/storage/object.o

# target to build an object file
src/storage/object.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/storage/object.c.o
.PHONY : src/storage/object.c.o

src/storage/object.i: src/storage/object.c.i
.PHONY : src/storage/object.i

# target to preprocess a source file
src/storage/object.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/storage/object.c.i
.PHONY : src/storage/object.c.i

src/storage/object.s: src/storage/object.c.s
.PHONY : src/storage/object.s

# target to generate assembly for a file
src/storage/object.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/storage/object.c.s
.PHONY : src/storage/object.c.s

src/utils/compare.o: src/utils/compare.c.o
.PHONY : src/utils/compare.o

# target to build an object file
src/utils/compare.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/utils/compare.c.o
.PHONY : src/utils/compare.c.o

src/utils/compare.i: src/utils/compare.c.i
.PHONY : src/utils/compare.i

# target to preprocess a source file
src/utils/compare.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/utils/compare.c.i
.PHONY : src/utils/compare.c.i

src/utils/compare.s: src/utils/compare.c.s
.PHONY : src/utils/compare.s

# target to generate assembly for a file
src/utils/compare.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/utils/compare.c.s
.PHONY : src/utils/compare.c.s

src/utils/hash.o: src/utils/hash.c.o
.PHONY : src/utils/hash.o

# target to build an object file
src/utils/hash.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/utils/hash.c.o
.PHONY : src/utils/hash.c.o

src/utils/hash.i: src/utils/hash.c.i
.PHONY : src/utils/hash.i

# target to preprocess a source file
src/utils/hash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/utils/hash.c.i
.PHONY : src/utils/hash.c.i

src/utils/hash.s: src/utils/hash.c.s
.PHONY : src/utils/hash.s

# target to generate assembly for a file
src/utils/hash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/utils/hash.c.s
.PHONY : src/utils/hash.c.s

src/utils/path.o: src/utils/path.c.o
.PHONY : src/utils/path.o

# target to build an object file
src/utils/path.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/utils/path.c.o
.PHONY : src/utils/path.c.o

src/utils/path.i: src/utils/path.c.i
.PHONY : src/utils/path.i

# target to preprocess a source file
src/utils/path.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/utils/path.c.i
.PHONY : src/utils/path.c.i

src/utils/path.s: src/utils/path.c.s
.PHONY : src/utils/path.s

# target to generate assembly for a file
src/utils/path.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git.dir/build.make CMakeFiles/git.dir/src/utils/path.c.s
.PHONY : src/utils/path.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... git"
	@echo "... src/cmd/catfile.o"
	@echo "... src/cmd/catfile.i"
	@echo "... src/cmd/catfile.s"
	@echo "... src/cmd/hashobject.o"
	@echo "... src/cmd/hashobject.i"
	@echo "... src/cmd/hashobject.s"
	@echo "... src/cmd/init.o"
	@echo "... src/cmd/init.i"
	@echo "... src/cmd/init.s"
	@echo "... src/cmd/lstree.o"
	@echo "... src/cmd/lstree.i"
	@echo "... src/cmd/lstree.s"
	@echo "... src/cmd/writetree.o"
	@echo "... src/cmd/writetree.i"
	@echo "... src/cmd/writetree.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/storage/object.o"
	@echo "... src/storage/object.i"
	@echo "... src/storage/object.s"
	@echo "... src/utils/compare.o"
	@echo "... src/utils/compare.i"
	@echo "... src/utils/compare.s"
	@echo "... src/utils/hash.o"
	@echo "... src/utils/hash.i"
	@echo "... src/utils/hash.s"
	@echo "... src/utils/path.o"
	@echo "... src/utils/path.i"
	@echo "... src/utils/path.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

